Seite für Erstifahrt hinzugefügt
ini-physik/inisite pull request #9
Opened 2016-10-05 14:40 UTC by maschatron

Noch ohne Inhalt, da warte ich noch auf Mail von Clara, Emma oder Leo

2016-10-05 19:19 UTC, mattimo commented
Topp, sieht super aus, fehlt ja nur noch der Text ;-)

2016-10-10 22:21 UTC, fabianfreyer requested changes

2016-10-10 22:21 UTC, fabianfreyer commented on layouts/index.html
> +					<a href="/iniyourface">Das sind wir...</a>
Das ist eigentlich ein unverwandter change, der kann eigentlich rausrebased werden.

2016-10-10 22:21 UTC, fabianfreyer commented on layouts/inibling/menu.html
> +			<li><a href="/iniyourface">Ini Your Face</a></li>
Ebenfalls iniyourface, sollte rausrebased werden.

2016-10-11 07:32 UTC, mattimo reviewed
Gut, wird hochgeladen und gemerged sobald wieder Strom auf dem ew ist

2016-10-11 07:32 UTC, mattimo commented on layouts/inibling/menu.html
> +			<li><a href="/iniyourface">Ini Your Face</a></li>
Naja, das ist ja in einem commit der nur die Menüpunkte hinzugefügt, ist schon ok so

2016-10-11 12:49 UTC, maschatron commented on layouts/inibling/menu.html
> +			<li><a href="/iniyourface">Ini Your Face</a></li>
Hatte auch einzelne pull requests gestellt, aber die wurden einfach zu einem zusammengefügt...

2016-10-13 14:04 UTC, merged